<?php
/**
 * i-MSCP - internet Multi Server Control Panel
 * Copyright (C) 2010-2013 by i-MSCP team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @category    iMSCP
 * @package     iMSCP Roundcube auto-response plugin
 * @copyright   2010-2013 by i-MSCP team
 * @author 		Peter Wyss
 * @link        http://www.i-mscp.net i-MSCP Home Site
 * @license     http://www.gnu.org/licenses/gpl-2.0.html GPL v2
 */
 
$labels = array();
$labels['autoresponder']  = 'Auto Responder';
$labels['editautoresponder']  = 'Edit Auto Responder';
$labels['autorespondermessage']  = 'Message:';
$labels['enableautoresponder']  = 'Enable Auto Responder:';

$messages = array();
$messages['connecterror'] = 'Could not set auto response. Connection error.';
$messages['internalerror'] = 'Could not set auto response.';
$messages['nomessage'] = 'Please enter an auto responder message.';
?>
