<?php
/**
 * Roundcube configuration file - auto-generated by i-MSCP
 *     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 *
 * You can override this configuration file with the help of an event listener
 * listening on the i-MSCP backend 'onLoadTemplate' event. For instance:
 *
 * Perl code:
 *
 * use iMSCP::EventManager;
 * use iMSCP::File;
 *
 * iMSCP::EventManager->getInstance()->register('onLoadTemplate', sub {
 *   my ($target, $cfgTplName, $cfgTplContent) = @_;
 *
 *   # We do not want act if the target isn't Roundcube, or if the
 *   # configuration file isn't the main configuration file.
 *   return 0 unless lc $target eq 'roundcube' && $cfgTplName eq 'config.inc.php';
 *
 *   # Load custom Roundcube configuration file into the $cfgTplContent
 *   # variable.
 *   return 1 unless defined ${ $cfgTplContent } = iMSCP::File->new(
 *     filename => 'path/to/your/roundcube/conf/file'
 *   )->get();
 *
 *   0;
 * });
 *
 * 1;
 * __END__
 *
 * The code above has to be put in an i-MSCP listener file which needs to be
 * saved into the /etc/imscp/listeners.d directory. See the contrib directory
 * of the i-MSCP distribution for further details and/or examples about i-MSCP
 * listener files.
 */

$config = [];
$config['db_dsnw'] = 'mysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOSTNAME}:{DATABASE_PORT}/{DATABASE_NAME}';
$config['log_logins'] = true;
$config['log_session'] = true;
$config['default_host'] = 'localhost';
$config['imap_auth_type'] = 'PLAIN';
$config['imap_force_lsub'] = true;
$config['imap_log_session'] = true;
$config['imap_cache'] = 'apc';
$config['smtp_server'] = 'localhost';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['smtp_auth_type'] = 'PLAIN';
$config['log_dir'] = '{LOG_DIR}';
$config['temp_dir'] = '{TMP_DIR}';
$config['session_lifetime'] = 20;
$config['des_key'] = '{DES_KEY}';
$config['cipher_method'] = 'AES-256-CBC';
$config['product_name'] = 'i-MSCP Webmail';
$config['identities_level'] = 3;
$config['use_secure_urls'] = true;
$config['create_default_folders'] = true;
$config['quota_zero_as_unlimited'] = true;
$config['enable_spellcheck'] = true;
